### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by ch3ckmat3** [ReinBentdal/styled_widget#11]
Dart Team needs to adopt this one. Just awesome concept!
IS it production ready though?

**Comment by ReinBentdal** [comment]
It is not production ready yet. The milestone 0.1.0 aims to be the point where it's possible to use in production

**Comment by ReinBentdal** [comment]
It will probaly work OK in production right now. The reason it is not recomended yet is because there is still alot of features missing and it will also most likely have alot of changes too.
