### ISSUE TITLE
Support for TextSpans

### ISSUE THREAD

**Issue by fibbers** [ReinBentdal/styled_widget#12]
First of all: I was already using your division-library and now I'm using this. I like both very much! 👌

I was searching to achieve something like this:
```dart
Text.rich(
  TextSpan(
    children: <InlineSpan>[
      TextSpan(text: 'All data will be deleted and '),
      TextSpan(
        text: 'this cannot be undone!',
        style: TextStyle(
          color: Colors.red,
          fontWeight: FontWeight.bold,
        ),
      ),
    ],
  ),
),
```
but couldn't find anything similar in division or styled_widgets (I was looking for either `Txt.rich` or just `Txt(children:..)`, for styled_widgets `Text(..).rich/children(..)`).

Am I missing something or is this a possible future feature? If so, do you already have some ideas about this or do you need some inspiration? :)

**Comment by ReinBentdal** [comment]
I havent thought about that yet! I am always open for suggestions on how to do anything.

The implementation would be something like this:
```dart
Text.rich(TextSpan(children: [
  TextSpan(text: 'some text')
    .bold(),
  TextSpan(text: 'more text')
    .italic(),
])
```
I havent used TextSpan myself before so i am open to other suggestions.

I cannot guarantee that i actually will implement this feature eighter. At the moment i am developing the package by myself and my time is somewhat limited.
It is very easy to learn how the package works and to implement it by yourself if you want the feature, or want to contribute. I am very open for pull requests

**Comment by fibbers** [comment]
Ok cool, I have experimented already a bit.

The `Text` widget has 2 (mutual exclusive) constructors which makes this a bit harder since extensions can't have constructors, so I tried some things using static methods to achieve a 'short' API:

```dart
extension StyledTextWithSpans on Text {
  static Text withSpans(List<TextSpan> children) => Text.rich(TextSpan(
        children: children,
      ));
}

extension StyledTextSpan on TextSpan {
  ...
}

StyledTextWithSpans.withSpans([
  TextSpan(text: 'Regular text, and '),
  TextSpan(text: 'bold text').textColor(Colors.green).bold(),
]),
```
However, I realise that the static utility method might not be suitable to be included in this library (maybe in the Flutter framework itself or just in my own code), so it indeed comes down to the API you suggested.

I'll see if I can make a PR out of just the `TextSpan` extension.

**Comment by ReinBentdal** [comment]
Its best to keep it as close to "native flutter" as possible and only changing whats really needed. With the example i gave above the only thing that has to be implemented is the styled methods for `TextSpan`. And these method would basicly be the same as the styled methods for `Text`. Eighter you could just copy most of the methods from the `Text` extension, or they could share the same methods by having a common `mixin` which both of them include. I dont think the last option is currently possible.

If you just use `Text.rich()` it would make it a bit easier i think. As i said, rely as much as possible on the flutter framework.

Looking forward to seeing what you come up with!

**Comment by fibbers** [comment]
Thanks for helping out on this so quickly! 👍

**Comment by ReinBentdal** [comment]
#13 Feature implemented
