### ISSUE TITLE
Decoupling styles

### ISSUE THREAD

**Issue by moraispgsi** [ReinBentdal/styled_widget#15]
Hi, 
One issue that seems to be present when we decouple the styles is that the hot reload no longer works when the styles are changed (at least it is my experience with division), is there anything that can be done about this?

**Comment by ReinBentdal** [comment]
The issue occurs simply because how hot reload works. It's only the build method that reloads. As far as I know there is no way around that

**Comment by moraispgsi** [comment]
Can you think of a solution for this? Like a flag or something, forcing the styles to be recalculated somehow.

**Comment by ReinBentdal** [comment]
As of right now am not shure of any solution

**Comment by moraispgsi** [comment]
I think that in this package the issue should not arise because the widgets are wrapped during the build method.

**Comment by moraispgsi** [comment]
After searching for a solution for a while I stumbled upon this link https://flutter.dev/docs/development/tools/hot-reload. Using getters (get keyword) works properly.

**Comment by moraispgsi** [comment]
Here is an example:

```
class Styles {
  static TextWrapper get primaryButton =>
      (Text text) => text.fontSize(14).textColor(Colors.lightBlue);
}
```

**Comment by ReinBentdal** [comment]
By defining the variable not as final, hot reload will apply to the variable
