### ISSUE TITLE
List conversion not working

### ISSUE THREAD

**Issue by kwado-tech** [ReinBentdal/styled_widget#23]
Thanks for this awesome package.
I cant seem to use toColumn() or toRow() conversion methods in my list.
It always gives an error since i cant find toColumn() and toRow() extension methods in my list.

Thanks in advance for the assist.

**Comment by ReinBentdal** [comment]
Hello, the reason is simply because the feature isn't in a release yet. My bad of updating the example before it being in a release

**Comment by kwado-tech** [comment]
Okay thanks for your quick reply.
Fixed it in my case by implementing your List extension methods. But an update will be good.

**Comment by moraispgsi** [comment]
@chrisoftech You can add the dependency like this for the latest features pushed to this repo.
pubspec.yaml
```
  styled_widget:
    git: https://github.com/ReinBentdal/styled_widget.git
```
