### ISSUE TITLE
[elevation] not respecting [borderRadius]

### ISSUE THREAD

**Issue by jhoogstraat** [ReinBentdal/styled_widget#25]
The elevation shadow does not clip to the borderRadius in the example code.

![elevation_borderRadius](https://user-images.githubusercontent.com/34964599/74085533-0e9f2e00-4a7a-11ea-8e9e-447bd08a6900.png)

**Comment by ReinBentdal** [comment]
This is now fixed. The way to get it working now is to define the borderRadius and elevation/boxShadow by each other like this:
```dart
Widget
  ...
  .borderRadius(all: 10)
  .elevation(10)
  ...
```
They will then be combined to a `DecoratedBox` behind the scenes
