### ISSUE TITLE
Stacks support

### ISSUE THREAD

**Issue by gloomie** [ReinBentdal/styled_widget#29]
Is it possible to create Stacks and position them to a specific percentage of their parent width,heigh?

Thanks for your work with styled_widget, it is fantastic!

**Comment by ReinBentdal** [comment]
Do you mean the widget `Positioned`? Did`nt quite get what you meant.

**Comment by gloomie** [comment]
Yes! I would like to use styled for all my widgets and I cant find how I
would position a stack child within the stack.

Maybe something like [ ].toStack is what actually missing. In that case,
however, I also wonder how for example someone would give positioned
arguments to a container in the children list.

**Comment by ReinBentdal** [comment]
`toStack` actually already exist.
```dart
<Widget>[
  // list of widgets
].toStack()
```
But I think to just use the normal Stack widget is just as good or even better.
A implementation of the `Poditioned` widget is on my to-do list

**Comment by gloomie** [comment]
Oh, nice - I didnt notice. Many thanks!
