### ISSUE TITLE
Margin not available?

### ISSUE THREAD

**Issue by ninest** [ReinBentdal/styled_widget#30]
I tried adding `.margin()`, but the error is 
```
The method 'margin' is not defined for the class 'Widget'.
```
Are there any ways to use margin in this plugin?

**Comment by ninest** [comment]
Is padding supposed to be used instead? I just realized that order DOES matter in styled_widget, while it did not in Division.

**Edit**
It seems that a `.padding()` acts more like margin. 

```
Container(
  child: SomeWidget().padding()  // this acts like SomeWidget's padding
).padding()  // this acts like SomeWidget's margin
```

Is this correct?

**Comment by ReinBentdal** [comment]
That is correct.

```dart
SomeWidget()
  .padding(all: 10) // padding
  .backgroundColor(Colors.amber)
  .padding(all: 10) // margin
```

**Comment by ninest** [comment]
I tried doing the same for a container:
```
Container(
  height: 200,
  child: Wid()
)
  .padding(
    all: 10
  )
  .borderRadius(
    all: 5,
  )
  .padding(
    all: 10,
  );
```

However, I get the error:
```
The expression doesn't evaluate to a function, so it can't be invoked.
```

So how do you put a padding for a container?
