### ISSUE TITLE
Add size(w,h) + 9 alignment options: center(), centerLeft() etc

### ISSUE THREAD

**Issue by esDotDev** [ReinBentdal/styled_widget#32]
I often find myself having to chain both width and height, 
**width(50).height(50)** would read better as **size(50,50)**

Additionally, when alignment things, it can be overly verbose:
**.alignment(Alignment.center)** could just be **center()**

**Comment by ReinBentdal** [comment]
As for width and height you can use `constraints`. For center() I think we are better of not including it. I think it then again would be too little verbose. What I am dreaming about is the possibility to omit the classname/enum if it's expected through the dart language to enable this: . alignment (.center). 
https://github.com/dart-lang/language/issues/357

**Comment by esDotDev** [comment]
Ooh that would be nice :) 

Still I center stuff _a lot_, would be really handy to just have _center()_. All of the other ones are less important imo. 

Another option would be to allow us to enter the raw values, like this would be really flexible:
_alignmentRaw(0,0)_

**Comment by ReinBentdal** [comment]
For now i wont add this. I want to keep the package simple. What i mean by that is to keep the package verbose and to have as few special cases as possible, like `center`. The same goes for `alignmentRaw` since you can already write `alignment(Alignment(x,y))`

I will keep this issue open for now.

**Comment by esDotDev** [comment]
Ok, I understand that philosophy, but in a library that is all about syntactic sugar, I'd argue, just pour on the sugar! It's not like its complex enough to be confusing, the align 'shortcuts' could all just serve as proxies for the main align call, so there wouldn't really be any extra maintenance or testing required.

Regarding constraints, I'm getting an error that the function is not defined:
![image](https://user-images.githubusercontent.com/736973/75811867-6ca5f500-5d4a-11ea-9aec-a5f9c0ab86b0.png)

It seems to be trying to use the .constraints property instead of the extension. Which affects at Container, IconButton, and probably many others. 

fwiw, I'm on latest master.

**Comment by ReinBentdal** [comment]
You should have opened a new issue regarding the bug. Anyways the problem is sorted in a upcoming release!

**Comment by ReinBentdal** [comment]
In v. 0.2.1 `center` is added, but as an `Center()` widget, not `Align(alignment: Alignment.center)`
