### ISSUE TITLE
Add Flexible() 

### ISSUE THREAD

**Issue by esDotDev** [ReinBentdal/styled_widget#33]
Seems curious that these are missing?

**Comment by ReinBentdal** [comment]
Which version are you using. Expanded got recently added

**Comment by esDotDev** [comment]
Oh srry! I guess I saw that Flexible is missing, and assumed it's counterpart Expanded was as well.

**Comment by esDotDev** [comment]
Did you close this because you don't think there's value in adding Flexible?

**Comment by ReinBentdal** [comment]
Flexible is available in 0.1.3

**Comment by esDotDev** [comment]
Thanks! And also thanks for the amazing lib, this is a game changer for styling :)
