### ISSUE TITLE
Why border radius doesn't work?

### ISSUE THREAD

**Issue by fedotxxl** [ReinBentdal/styled_widget#36]
Hello. I'm new to Flutter and trying to add border radius to a Container. Padding works as expected but border-radius doesn't. Can you explain why? How can I apply border radius to a Container?

```dart
Styled.widget(
            child: Container(
              child: Text(this.message.message).fontSize(18).textColor(this._getTextColor()),
            ))
            .padding(all: 10.0)
            .backgroundColor(this._getBackgroundColor())
            .borderRadius(all: 8.0)
```

**Comment by ReinBentdal** [comment]
Hello, (almost) all method in styled_widget initiates a new widget. For example `.padding()` creates `Padding()` and `.backgroundColor(Colors.blue)` creates `DecoratedBox(decoration: BoxDecoration(color: Colors.blue))`.
Therefore when you apply `backgroundColor`, then `borderRadius()` they will create two different widgets, but you want them to be inside the same widget to apply the border radius to the background color. To do so you need to use the `decorated` method;
```dart
final TextStyle _textStyle = TextStyle(
  fontSize: 18, 
  color: this._getTextColor(),
);

Text(this.message.message, style: _textStyle)
  .padding(all: 10.0)
  .decorated(
    color: this._getBackgroundColor(),
    borderRadius: BorderRadius.circular(8.0),
  );
```
In your example `Styled.widget()` and `Container` serve no purpose so they can be omitted.
