### ISSUE TITLE
Add support for (toColumn/toRow).separator

### ISSUE THREAD

**Issue by esDotDev** [ReinBentdal/styled_widget#38]
Would it be possible to add a separator builder, so we can do something like:
```
[
   Text(),
   Text(),
].toColumn(separator: ()=>SizedBox(height: 8))
```

**Comment by ReinBentdal** [comment]
I will keep this open for now until i have investigated the possibilities!

**Comment by ReinBentdal** [comment]
Its easy to implement
```dart
children: spacer == null
  ? children
  : children.expand((child) => [child, seperator]).toList(),
```
Will add it in the next release!

**Comment by esDotDev** [comment]
Oh nice, that's way cleaner than my implementation! Thanks!

(Only thing is, we don't really want it on the end, easy enough to add padding to the start/end as needed)

**Comment by ReinBentdal** [comment]
Do you mean:
```dart
Widget(),
Seperator(),
Widget(),
Seperator (), // remove this
```
That should be added. Easy to just pop the last element with `.removeLast()`.

**Comment by esDotDev** [comment]
Yes exactly, from usage, that is almost always what I want to do. We can easily tack on some padding to the start and end with .padding() and it's more readable as well.

This mimics ListView.separated() as well:
https://api.flutter.dev/flutter/widgets/ListView/ListView.separated.html

**Comment by ReinBentdal** [comment]
added in v. 0.2.1
