### ISSUE TITLE
Add support for IgnorePointer

### ISSUE THREAD

**Issue by esDotDev** [ReinBentdal/styled_widget#42]
Since we're already supporting gestures, it would be nice to be able to say `ignorePointer()`, or even:
`gestures(ignore: someCondition, onTapUp: someHandler)` .

**Comment by ReinBentdal** [comment]
Closing since there is already an issue about this: #35 . Please continue the discussion there instead

**Comment by esDotDev** [comment]
Oh man, sorry, total brain fart
