### ISSUE TITLE
Is there any widget like Parent() on division

### ISSUE THREAD

**Issue by RakaAlrian** [ReinBentdal/styled_widget#44]
Hi, first of all I really love your division library. I used Parent() a lot to create "wrap_content" layout on flutter. How can I build widget like Parent() using styled_widget? Thanks.

**Comment by ReinBentdal** [comment]
Hello, while quite lacking I would recommend you checking out the Wiki page of this repository.
styled_widget uses a different styling paradigm despite looking very similar to Division. To achieve something like Parent you could do something like:
```dart
final _myStyle = ({Widget child}) => child
    . alignment (Alignment.center)
    // etc

_myStyle(child: SomeWidget);
```

Does this make sense?

**Comment by RakaAlrian** [comment]
I want to do something like this 

```
Container(
      width: width,
      padding: EdgeInsets.all(6),
      decoration:
          BoxDecoration(color: color, borderRadius: BorderRadius.circular(10)),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[],
      ),
    )
```

I tried to use Container extension by styled_widget like this
```
Container(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[],
      )
).width(width).padding(all: 6).decorated(color: color, borderRadius: BorderRadius.circular(10))
```
but it shows different result.
I tried using parent like one of your example, like this
```
final style = ({Widget child}) => Styled.widget(child: child)
        .width(width).padding(all: 6).decorated(color: color, borderRadius: BorderRadius.circular(10))
Container(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[],
      )
).parent(style)
```
and this
```
final style = ({Widget child}) => Styled.widget(child: child)
        .width(width).padding(all: 6).decorated(color: color, borderRadius: BorderRadius.circular(10))
style(
   child: Container(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[],
        )
      )
)
```
but it shows different result too.

**Comment by ReinBentdal** [comment]
The reason it gives a different result is because each extension method creates a new widget. Therefore if you want to style with multiple decoration parameters you need to use the method called `.decorated()` and define borderRadius and such inside this. You probably didn't see the borderRadius in your example since it's defined in a different widget than the background color.

**Comment by RakaAlrian** [comment]
Sorry for slow response. I think I'm doing right about `.decorated()` implementation on my previous comment. I found out that extension `.padding()` that make it shows different result. It looks like it giving a margin instead of giving a padding like it names.

**Comment by ReinBentdal** [comment]
The order which you add the extensions matter. If you insert the padding after decorated it works like margin. If before it works like padding

**Comment by RakaAlrian** [comment]
Wait a minute, I think I just understand what you said about "each extension method creates a new widget", I realize that `.padding()` wrap the current widget with `Padding()` widget, that's why it looks like giving a margin. Thanks for your kind explanation. I'll close this issue for now 😄
