### ISSUE TITLE
Null Safety Migration

### ISSUE THREAD

**Issue by vance-liu** [ReinBentdal/styled_widget#54]
Dart Null Safety is in beta and packages should start to be migrated.
[Migration guide](https://dart.dev/null-safety/migration-guide)

**Comment by ReinBentdal** [comment]
Thanks for the reminder. Studies and other projects are currently mye priority. I therefore cannot guarantee a fast adoption

**Comment by vance-liu** [comment]
Thanks for your awesome work. Maybe i can help if you need, push a pr and upgrade example to Flutter2 in next week.

**Comment by ReinBentdal** [comment]
That would be awesome! Thanks for the feedback

**Comment by esase** [comment]
Hello guys, yes it's a very actual now days
