### ISSUE TITLE
Make extension params nullable

### ISSUE THREAD

**Issue by f69** [ReinBentdal/styled_widget#61]
Please, make extension params nullable, where underlying class params are nullable.
For example, now (in version 0.3.1) you cant write:

`Text(message).textColor(isError ? Colors.red : null)`

to change text color (from default) only for some condition.
All params of TextStyle class are nullable.

**Comment by ReinBentdal** [comment]
Yes that should be fixed. 

I would suggest adding styles applied to a widget in the traditional way
```dart
Text(message, style: TextStyle(color: isError ? Colors.red : null))
```
The method applied to the Text widget mutates the original widget before applying the new changes. This is less performant compared to applying style when the widget is created.

**Comment by ReinBentdal** [comment]
fixed
