### ISSUE TITLE
[StatelessWidget] and [StatefulWidget] integration

### ISSUE THREAD

**Issue by ReinBentdal** [ReinBentdal/styled_widget#9]
Thinking about the posibility to wrap each styled widget with eighter a stateless or stateful widget.

```dart
Styled.widget((Widget child) => child.alignment(Alignment.center))
```

Something like this possible?
```dart
Styled.widget((useState, state) => ...)
```

**Comment by elhe26** [comment]
Adding the state will add an extra layer of complexity. We can manage the styling parameters using state management techniques (provider, bloc, etc...). Could you please explain the concept of adding this?

Awesome package btw.

**Comment by ReinBentdal** [comment]
Due to more readable and compact code its much easier to combine what would previously be multiple stateless or stateful widgets into one bigger widget. In some cases a complete stateless or stateful widget could transform into a simple styled_widget.
Bigger stateless and stateful widgets means that more widgets would have to rebuild when a state changes. 
So the point is to reduce the number of widgets that has to rebuild by wrapping them in a stateful or stateless widget. 
I havent investigated if this actually would increse performance, and as you said, it would be an extra layer of complexity.
At this moment it is about throwing possibilities at the table and see whats possible.

**Comment by ReinBentdal** [comment]
will close this for now because i think its not possible to improve performance by implementing this
